version: '3.9'
services:
        apache:
                image: httpd:latest
                container_name: desafio-dio-apache-app
                ports:
                        - '80:80'
                volumes:
                        - ./www:/usr/local/apache2/htdocs
